/**
 * @author Erwan Yhuellou
 * @created 26/01/2020
 * @description Covering PAD Class
 */
 @isTest
private class PAD_Test {
/*
    @testSetup static void setup() {
        
        User u = UserInfo.getUserId();
        u.LPCR_ByPassTrigger__c = 'SM001_TestIfByPassed';
        update u;

        // Create common test accounts
        UM002_TestDataFactory tdf = new UM002_TestDataFactory();
        Account a = tdf.AccountTdf.create('Account Test');
        insert a;
    }

    static testMethod void validatePAD() {

        System.AssertEquals(PAD.canTrigger('SM001_TestIfByPassed'), true, 'User can by Pass SM001_TestIfByPassed');

        PAD.log('SM001_TestIfByPassed', 'method', 'description', 'ok');
        PAD.log('SM001_TestIfByPassed', 'method', 'description');
        PAD.limits();
        
    }
*/
}