/**
 * @author Erwan Yhuellou
 * @created 26/01/2020
 * @description Covering UM002_TestDataFactory Class
 */
 @isTest
private class UM002_TestDataFactory_Test {
/*
    @testSetup static void setup() {
        
        // Create Factory
        UM002_TestDataFactory tdf = new UM002_TestDataFactory();

        Account a = tdf.AccountTdf.create('Account Test');
        insert a;

        Case a = tdf.CaseTdf.create('Account Test');
        insert a;

        Oppoertunity a = tdf.OppoertunityTdf.create('Account Test');
        insert a;

        Contact a = tdf.CaontactTdf.create('Account Test');
        insert c;
    }

    static testMethod void validatePAD() {

        Account tmp = [Select Id, Name from Account where name like 'Account Test'];

        System.AssertNotEquals(tmp, null, 'Account not created');
        
    }
*/
}