public class UM010_Constant {
    //use capital letters and variable defined as object & field, example:   
    //public static final String RT_ACCOUNT_CRECHE
    public static final String MODIFICATION_ADRESSE_CONTACT_PARENT = 'Modification_Adresse_Contact_Parent';
    public static final String MODIFICATION_AUTORITE_PARENTALE = 'Modification_Autorite_Parentale';
    public static final String MODIFICATION_NUMERO_ALLOCATAIRE = 'Modification_Numero_Allocataire';
    public static final String Modification_Situation_Handicape_Enfant = 'Modification_Situation_Handicape_Enfant';
    public static final String MODIFICATION_TYPE_ACCUEIL = 'Modification_Type_Accueil';
    public static final String MODIFICATION_TYPE_PLANNING = 'Modification_Type_Planning';
    public static final String MODIFICATION_NOMBRE_ENFANT_FRATRIE = 'Modification_Nombre_Enfant_Fratrie';
    public static final String MODIFICATION_MONTANT_RESSOURCE = 'Modification_Montant_Ressource';
    public static final String MODIFICATION_NOMBRE_JOUR_CONGE = 'Modification_Nombre_Jour_Conge';
    public static final String DATE_FIN_CONTRAT = 'Date_Fin_Contrat';
    public static final String MODIFICATION_SECTION = 'Modification_Section';
    public static final String DATE_NAISSANCE_ENFANT = 'Date_Naissance_Enfant';
    public static final String MODIFICATION_MODE_GARDE = 'Modification_Mode_Garde';
    public static final String MODIFICATION_SITUATION_FAMILIALE = 'Modification_Situation_Familiale';
    public static final String MODIFICATION_NOMBRE_MOIS_MENSUALISE = 'Modification_Nombre_Mois_Mensualise';
    public static final String MODIFICATION = 'Modification';
    public static final String MODIFICATION_DELAI_CARENCE = 'Modification_Delai_Carence';
    public static final String MODIFICATION_HEURE_SUPPLEMENTAIRE_MAC = 'Modification_Heure_Supplementaire_MAC';
    public static final String MODIFICATION_HEURE_OCCASIONNEL_MAC = 'Modification_Heure_Occasionnel_MAC';
    public static final String MODIFICATION_NOMBRE_CONGES_MAC = 'Modification_Nombre_Conges_MAC';
    public static final String MODIFICATION_HEURE_DEDUITE_MAC = 'Modification_Heure_Deduite_MAC';
    public static final String NOMBRE_DE_REPAS = 'Nombre_de_repas';
    public static final String MODIFICATION_FACTURATION_ADAPTATION = 'Modification_Facturation_Adaptation';
    public static final String COMMENTAIRE_INDIVIDUEL_FACTURE = 'Commentaire_Individuel_Facture';
    public static final String COMMENTAIRE_GLOBAL_FACTURE = 'Commentaire_Global_Facture';
    public static final String ABSCENCE = 'Abscence';
    public static final String NB_HEURES_REALISEE = 'NB_Heures_Realisee';
    public static final String TRAITEMENT_JOUR_FERIE = 'Traitement_Jour_Ferie';
    public static final String REGULARISATION = 'Regularisation';

}