public class UM010_Constant {

    // OTHER
    public static final String CRECHE_LPCR = 'Crèche LPCR : ';

    // CALLOUT LOG
    public static final String LOG_SEND_DOC_TO_GED = 'Appel Externe ENVOIE DOCUMENT GED LPCR';
    public static final String LOG_LIST_DOC = 'Appel Service Externe REF DOC LIST';
    public static final String LOG_REF_DOC_REC = 'Appel Service Externe REF DOC RECUP';
    public static final String LOG_REF_SENDMAIL = 'Appel Service Externe REF SENDMAIL';

    // RESULTS
    public static final String ERROR = 'Error';
    public static final String SUCCESS = 'Success';

}